version: '3.8'

services:
  backend:
    image: m4tth3wg/adrian_ttt_backend:auth
    environment:
      - API_DOMAIN=${API_DOMAIN}
    ports:
      - 8080:8080

  frontend:
    image: m4tth3wg/adrian_ttt_frontend:auth
    environment:
      - REACT_APP_API_DOMAIN=${API_DOMAIN}
    ports:
      - 3000:3000

    depends_on:
      - backend