version: '3.8'

services:
  backend:
    build:
      context: ./backend/TicTacToeBackend/
      target: final
    ports:
      - 8080:8080
      - 8081:8081

  frontend:
    build: 
        context: ./frontend
        args:
          DEFAULT_API_DOMAIN: "http://localhost"
          DEFAULT_API_PORT: 8080
    ports:
      - 3000:3000

    depends_on:
      - backend