version: '3.8'

services:
  backend:
    image: m4tth3wg/tic-tac-toe-cloud-backend:latest
    ports:
      - 8080:8080

  frontend:
    image: m4tth3wg/tic-tac-toe-cloud-frontend:latest
    environment:
      - REACT_APP_API_DOMAIN=${API_DOMAIN}
    ports:
      - 3000:3000

    depends_on:
      - backend